In [6]:
#Checking the time between this list and numpy
import time 
import numpy as np
size = 1_000_000
list1 = list(range(size))
npa = np.array(list1)
start = time.time()
numpy_squares = npa ** 2
end = time.time()
print(end - start)

0.007124662399291992


In [2]:
import time 
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
list_squares = [x**2 for x in list1]
end = time.time()
print("Python list square time:", end - start)

Python list square time: 0.17847037315368652


In [1]:
#Creating numpyu arrays
import numpy as np
arr = np.array([1,2,3,4,5])



In [4]:
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
#numpy indexing 
import numpy as np
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9] , [10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
flat =arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat[0:13]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
flat[::2]

array([ 1,  3,  5,  7,  9, 11])

In [10]:
#Create a 3×3 array filled with random numbers and print its shape.
arr1 = np.array([[1,2,3] , [76,23,100] , [300,29,101]])
print(arr1.shape)

(3, 3)


In [11]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
arr = np.array([[2.2 ,2.00986 , 3.45564] , [3.4 , 100.000 , 1000.000]])
intarr = arr.astype(int)
print(intarr)

[[   2    2    3]
 [   3  100 1000]]


In [13]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr = np.array([1, 2, 3, 4, 5])
mask = arr % 2 ==0
even = arr[mask]
print(even)

[2 4]


In [14]:
arr = np.array([[1,2,3] , [3,4,5] , [6,7,8]])
print(arr)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [15]:
arr[0:2 , 1:3]

array([[2, 3],
       [4, 5]])

In [16]:
#Numpy Data Types

import numpy as np
arr = np.array([1,2,3,4,5,6,90])
print(arr.dtype)

int64


In [17]:
arr.astype("float64")

array([ 1.,  2.,  3.,  4.,  5.,  6., 90.])

In [20]:
#broadcasting in numpy means like no need of running the loop as we run in the list
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
power = arr1 ** 2
print(power)

[ 1  4  9 16 25 36]


In [22]:
power + 10

array([11, 14, 19, 26, 35, 46])